### ISSUE TITLE
openjscad.org is down

### ISSUE THREAD

**Issue by DeadlyDad** [JamesNewton/HybridDiskEncoder#4]
Using replacement site (https://www.openjscad.xyz/#https://raw.githubusercontent.com/JamesNewton/HybridDiskEncoder/master/encoderdisk.jscad) gives 

> ERROR:
> Uncaught ReferenceError: params is not defined
> Line: 55

Pasting the script into https://joostn.github.io/OpenJsCad/ causes

> ReferenceError: params is not defined
> Stack trace:
> ReferenceError: params is not defined
>     at main (blob:https://joostn.github.io/11b3706f-4455-4d5b-9b60-fdec83e3ec4d:33:13)
>     at Function.OpenJsCad.runMainInWorker (https://joostn.github.io/OpenJsCad/src/openjscad.js:312:18)
>     at blob:https://joostn.github.io/11b3706f-4455-4d5b-9b60-fdec83e3ec4d:367:96

**Comment by DeadlyDad** [comment]
...and, of course, using openjscad.com works just fine.  :sigh:

**Comment by JamesNewton** [comment]
I'm happy openjscad.com is up... I thought it was gone for a while? But I can't get it to load in one gasp:
https://openjscad.com/#https://raw.githubusercontent.com/JamesNewton/HybridDiskEncoder/master/encoderdisk.jscad
does NOT work, it sticks on loading the URL and shows:
Script error.
Line: 0,col: 0
()
in the upper left. 

If I just open the site, then paste in the code, it does indeed work. 

But I think the issue is that the new versions (.xyz and github hosted) don't support the parameter panel?

**Comment by JamesNewton** [comment]
Edited the readme to compensate.
