### ISSUE TITLE
information on leds and photodiodes used

### ISSUE THREAD

**Issue by AldrickPeter** [JamesNewton/HybridDiskEncoder#7]
Hello sir, 
me and my friend are trying to make the hybrid disk encoder for a SCARA for our final year engineering project. We tried and tested a few components and we can never get it right. Please tell us the specs of the led and the photodiode that you used or even the component name. 
Thankyou

**Comment by JamesNewton** [comment]
Glad to see someone trying! I've added the info in the Electronics section in the read.me
https://github.com/JamesNewton/HybridDiskEncoder?tab=readme-ov-file#electronics

Here is a shopping card from Mouser with all the parts you need. Obviously, remove whatever you already have, and keep in mind that it might be best to increase qty's to get a price break and have extra in case of magic smoke release. 
https://www.mouser.com/ProjectManager/ProjectDetail.aspx?AccessID=f8ccd3c2d6

Whatever you do, start with just one connected, use a light source that it can see, and just watch the output of the ADC via the serial monitor until you have a good signal there. It's easy to get the sensor connected backwards, or have the trim pot set wrong, or to just wire it incorrectly. Take small steps, verify along the way. I started with just the trim pot voltage divider, with one side to ground, the other to 3.3, and then turned the knob until I saw a changing value in the ADC. Turns out I was 1. monitoring the wrong pin, 2. Didn't have the ground pin actually connected. Then I replaced the jumper to 3.3 with the photodiode and setup a slow flashing light until I got that signal through. I 100% had it connected backwards when I started. Here is the video of the first test setup
https://photos.app.goo.gl/wynsWwThrSx9u5cn8

**Comment by AldrickPeter** [comment]
Sir, thank you so much for taking the time to put all this together! I am grateful for your generosity in sharing your knowledge and experience. It has been a huge help for me! Thank you!! 🙏🙏

**Comment by JamesNewton** [comment]
@AldrickPeter Please do let me know how it goes: JamesNewton@MassMind.org
